export const vdsBackgroundColorError: "#FBE6E6";
export const vdsBackgroundColorWarning: "#FFF5E2";
export const vdsBackgroundColorSuccess: "#E3F8ED";
export const vdsBackgroundColorInformation: "#E5EFF5";
export const vdsBorderRadiusNone: 0;
export const vdsBorderRadiusBase: "0.5rem";
export const vdsBorderRadiusSecondary: "0.25rem";
export const vdsBorderRadiusCircle: "50%";
export const vdsBorderError: "2px solid #DD3131";
export const vdsBorderWarning: "2px solid #FFAE0C";
export const vdsBorderSuccess: "2px solid #15C26B";
export const vdsBorderInformation: "2px solid #2A77AA";
export const vdsBorderColorError: "#DD3131";
export const vdsBorderColorWarning: "#FFAE0C";
export const vdsBorderColorSuccess: "#15C26B";
export const vdsBorderColorInformation: "#2A77AA";
export const vdsBoxShadow0: "none";
export const vdsBoxShadow1: "0 2px 4px 0 rgba(17,22,26,0.16), 0 0 4px 0 rgba(17,22,26,0.08), 0 4px 8px 0 rgba(17,22,26,0.04)";
export const vdsBoxShadow2: "0 4px 8px 0 rgba(17,22,26,0.16), 0 4px 8px 0 rgba(17,22,26,0.08), 0 8px 16px 0 rgba(17,22,26,0.04)";
export const vdsBoxShadow3: "0 0 8px 0 rgba(17,22,26,0.06), 0 4px 16px 0 rgba(17,22,26,0.08), 0 8px 12px 0 rgba(17,22,26,0.06), 0 16px 24px 0 rgba(17,22,26,0.04)";
export const vdsBoxShadow4: "0 4px 12px 0 rgba(17,22,26,0.06), 0 4px 24px 8px rgba(17,22,26,0.12), 0 8px 16px 0 rgba(17,22,26,0.06), 0 32px 40px 0 rgba(17,22,26,0.02)";
export const vdsBoxShadow5: "0 4px 12px 0 rgba(0,0,0,0.08), 0 8px 32px 8px rgba(17,22,26,0.12), 0 16px 24px 8px rgba(17,22,26,0.06), 0 64px 48px 8px rgba(17,22,26,0.06)";
export const vdsBreakpointXs: "20rem";
export const vdsBreakpointSm: "30rem";
export const vdsBreakpointMd: "48rem";
export const vdsBreakpointLg: "62rem";
export const vdsBreakpointXl: "73.75rem";
export const vdsColorCeruleanDarker: "#014052";
export const vdsColorCeruleanDark: "#017A9B";
export const vdsColorCerulean: "#02B3E4";
export const vdsColorCeruleanLight: "#53CBED";
export const vdsColorCeruleanLighter: "#A4E4F5";
export const vdsColorCeruleanLightest: "#F5FCFE";
export const vdsColorSlateDarker: "#11161A";
export const vdsColorSlateDark: "#1F2932";
export const vdsColorSlate: "#2E3D49";
export const vdsColorSlateLight: "#6D7780";
export const vdsColorSlateLighter: "#B4B9BD";
export const vdsColorSlateLightest: "#F7F7F8";
export const vdsColorSilverDarker: "#242A2F";
export const vdsColorSilverDark: "#454F58";
export const vdsColorSilver: "#657482";
export const vdsColorSilverLight: "#96A0AA";
export const vdsColorSilverLighter: "#C8CDD2";
export const vdsColorSilverLightest: "#F9F9FA";
export const vdsColorRedDarker: "#501212";
export const vdsColorRedDark: "#962121";
export const vdsColorRed: "#DD3131";
export const vdsColorRedLight: "#E87373";
export const vdsColorRedLighter: "#F3B5B5";
export const vdsColorRedLightest: "#FBE6E6";
export const vdsColorOrangeDarker: "#5C3F04";
export const vdsColorOrangeDark: "#9E6C07";
export const vdsColorOrange: "#FFAE0C";
export const vdsColorOrangeLight: "#FFC85A";
export const vdsColorOrangeLighter: "#FFE2A8";
export const vdsColorOrangeLightest: "#FFF5E2";
export const vdsColorGreenDarker: "#084627";
export const vdsColorGreenDark: "#0E8449";
export const vdsColorGreen: "#15C26B";
export const vdsColorGreenLight: "#60D69A";
export const vdsColorGreenLighter: "#ABE9CA";
export const vdsColorGreenLightest: "#E3F8ED";
export const vdsColorBlueDarker: "#0F2B3D";
export const vdsColorBlueDark: "#1D5174";
export const vdsColorBlue: "#2A77AA";
export const vdsColorBlueLight: "#6EA3C5";
export const vdsColorBlueLighter: "#B2CEE0";
export const vdsColorBlueLightest: "#E5EFF5";
export const vdsColorPurpleDarker: "#391B50";
export const vdsColorPurpleDark: "#6C3498";
export const vdsColorPurple: "#9F4CDF";
export const vdsColorPurpleLight: "#BE85E9";
export const vdsColorPurpleLighter: "#DCBFF3";
export const vdsColorPurpleLightest: "#F3EAFB";
export const vdsColorYellowDarker: "#554809";
export const vdsColorYellowDark: "#A88E12";
export const vdsColorYellow: "#ECC81A";
export const vdsColorYellowLight: "#F2DA63";
export const vdsColorYellowLighter: "#F8EBAD";
export const vdsColorYellowLightest: "#FDF8E4";
export const vdsColorTealDarker: "#014943";
export const vdsColorTealDark: "#018377";
export const vdsColorTeal: "#02CCBA";
export const vdsColorTealLight: "#53DCD0";
export const vdsColorTealLighter: "#A4EDE6";
export const vdsColorTealLightest: "#E1F9F7";
export const vdsColorMagentaDarker: "#5C1E2F";
export const vdsColorMagentaDark: "#AD3959";
export const vdsColorMagenta: "#FF5483";
export const vdsColorMagentaLight: "#FF8BAB";
export const vdsColorMagentaLighter: "#FFC1D2";
export const vdsColorMagentaLightest: "#FFEAF0";
export const vdsColorWhite: "#FFFFFF";
export const vdsColorBlack: "#000709";
export const vdsBaseDuration: "0.3s";
export const vdsBaseTiming: "ease";
export const vdsTransitionAll: "all 0.3s ease";
export const vdsFontFamilyText: "'Open Sans', sans-serif";
export const vdsFontFamilyCode: "'Source Code Pro', monospace";
export const vdsBaseFontUnit: "16";
export const vdsBaseFontSize: "16px";
export const vdsHeadingFontSizeH1: "2.5rem";
export const vdsHeadingFontSizeH2: "2rem";
export const vdsHeadingFontSizeH3: "1.5rem";
export const vdsHeadingFontSizeH4: "1rem";
export const vdsHeadingFontSizeH5: "0.75rem";
export const vdsHeadingFontSizeH6: "0.625rem";
export const vdsHeadingFontSizeH1Mobile: "2rem";
export const vdsHeadingFontSizeH2Mobile: "1.5rem";
export const vdsHeadingFontSizeH3Mobile: "1.125rem";
export const vdsHeadingFontSizeH4Mobile: "1rem";
export const vdsTextFontSize: "1rem";
export const vdsTextFontSizeSm: "0.875rem";
export const vdsTextFontSizeXs: "0.75rem";
export const vdsQuoteFontSize: "1.5rem";
export const vdsQuoteFontSizeMobile: "1.125rem";
export const vdsFontWeightLight: "300";
export const vdsFontWeightRegular: "400";
export const vdsFontWeightSemibold: "600";
export const vdsFontWeightBold: "700";
export const vdsFontWeightExtrabold: "800";
export const vdsGradientSilverCerulean: "linear-gradient(to bottom right, #F9F9FA, #F5FCFE)";
export const vdsGradientSilverSlate: "linear-gradient(to bottom right, #F9F9FA, #F7F7F8)";
export const vdsGradientPurpleCerulean: "linear-gradient(to bottom right, #DCBFF3, #A4E4F5)";
export const vdsGradientPurpleMagenta: "linear-gradient(to bottom right, #9F4CDF, #FF5483)";
export const vdsGradientTealPurple: "linear-gradient(to bottom right, #02CCBA, #9F4CDF)";
export const vdsGradientCeruleanTeal: "linear-gradient(to bottom right, #02B3E4, #02CCBA)";
export const vdsGradientMagentaYellow: "linear-gradient(to bottom right, #FF5483, #ECC81A)";
export const vdsGradientCeruleanPurple: "linear-gradient(to bottom right, #02B3E4, #9F4CDF)";
export const vdsGradientPurpleMagentaDark: "linear-gradient(to bottom right, #6C3498, #AD3959)";
export const vdsGradientTealPurpleDark: "linear-gradient(to bottom right, #018377, #6C3498)";
export const vdsGradientCeruleanTealDark: "linear-gradient(to bottom right, #017A9B, #018377)";
export const vdsGradientMagentaYellowDark: "linear-gradient(to bottom right, #AD3959, #A88E12)";
export const vdsGradientCeruleanPurpleDark: "linear-gradient(to bottom right, #017A9B, #6C3498)";
export const vdsLetterSpacing: "1.5px";
export const vdsBaseLineHeight: "28px";
export const vdsHeadingLineHeightH1: "4rem";
export const vdsHeadingLineHeightH2: "3rem";
export const vdsHeadingLineHeightH3: "2.5rem";
export const vdsHeadingLineHeightH4: "2rem";
export const vdsHeadingLineHeightH5: "1.5rem";
export const vdsHeadingLineHeightH6: "1rem";
export const vdsHeadingLineHeightH1Mobile: "3rem";
export const vdsHeadingLineHeightH2Mobile: "2.5rem";
export const vdsHeadingLineHeightH3Mobile: "2rem";
export const vdsHeadingLineHeightH4Mobile: "1.75rem";
export const vdsTextLineHeight: "2rem";
export const vdsTextLineHeightSm: "1.5rem";
export const vdsTextLineHeightXs: "1.5rem";
export const vdsQuoteLineHeight: "2.5rem";
export const vdsQuoteLineHeightMobile: "2rem";
export const vdsTextSelectionOpacity: "0.40";
export const vdsTextMaxWidthSm: "30rem";
export const vdsTextMaxWidthBase: "40rem";
export const vdsTextMaxWidthLg: "50rem";
export const vdsSpacingNone: "0";
export const vdsSpacingHalf: "0.25rem";
export const vdsSpacing1X: "0.5rem";
export const vdsSpacing2X: "1rem";
export const vdsSpacing3X: "1.5rem";
export const vdsSpacing4X: "2rem";
export const vdsSpacing6X: "3rem";
export const vdsSpacingInlineHalf: "0 0.25rem 0 0";
export const vdsSpacingInline1X: "0 0.5rem 0 0";
export const vdsSpacingInline2X: "0 1rem 0 0";
export const vdsSpacingInline3X: "0 1.5rem 0 0";
export const vdsSpacingInline4X: "0 2rem 0 0";
export const vdsSpacingInline6X: "0 3rem 0 0";
export const vdsSpacingInsetHalf: "0.25rem 0.25rem 0.25rem 0.25rem";
export const vdsSpacingInset1X: "0.5rem 0.5rem 0.5rem 0.5rem";
export const vdsSpacingInset2X: "1rem 1rem 1rem 1rem";
export const vdsSpacingInset3X: "1.5rem 1.5rem 1.5rem 1.5rem";
export const vdsSpacingInset4X: "2rem 2rem 2rem 2rem";
export const vdsSpacingInset6X: "3rem 3rem 3rem 3rem";
export const vdsSpacingStackHalf: "0 0 0.25rem 0";
export const vdsSpacingStack1X: "0 0 0.5rem 0";
export const vdsSpacingStack2X: "0 0 1rem 0";
export const vdsSpacingStack3X: "0 0 1.5rem 0";
export const vdsSpacingStack4X: "0 0 2rem 0";
export const vdsSpacingStack6X: "0 0 3rem 0";
export const vdsTextColor: "#11161A";
export const vdsTextSelectionColor: "#A4E4F5";
export const vdsTextColorError: "#501212";
export const vdsTextColorWarning: "#5C3F04";
export const vdsTextColorSuccess: "#084627";
export const vdsTextColorInformation: "#0F2B3D";
